### PR TITLE
Copy changes

### LINKED ISSUE #157: Improve Mozfest messaging on /about and /what-to-expect
Mitchell Baker shared a few edits for how we talk about Mozfest. We should work these into copy on the website and in other materials: 

* "continuing the momentum" sounds boring to me.  I know we did something like this at Whistler -- not reinventing, but delivering on the promise of before.  So the core idea may well be right, though even so it sounds boring!
* Past materials have focused on how many people are there, how many sessions, etc.  That might be right for those materials, but aren't as helpful in getting people to understand the core of it, why it's different from other places.  In other words, it gives a sense of the size and scale but is a bit self-referential and logistical.
* the media document talks about leadership development as being the core theme (and I like it!).  The webpage currently conveys mostly web literacy  to me.  "Teach and build" does not make me think of the incredible range of activities MozFest brings.  If feels like the Maker Party web literacy work to me.  Great work of course, but only a fraction of what makes MozFest so stimulating.

cc @Saallen @KevZawacki

### PR DESCRIPTION
**Pull request by mmmavis**
This fixes #157.

for PR reviewer (@ScottDowne? :stuck_out_tongue: ): 
use this url to view code difference: https://github.com/mozilla/2015.mozillafestival.org/pull/166/files?w=1 (this ignore whitespace diff)

### CODE REVIEW

**Comment by mmmavis** [comment]
yo @ScottDowne can i assign this to you? :dancer:

**Comment by ScottDowne** [comment]
Yup, you can totally feel free to assign me reviews :)

**Comment by ScottDowne** [comment]
Why is github adding a bunch of weird whitespace changes to the diff? Super not needed as I don't see any whitespace changes.

**Comment by ScottDowne** [comment]
I kinda want to figure out why it's tracking whitespace changes while there are no whitespace changes.

Makes git blame hard.

**Comment by mmmavis** [comment]
> I kinda want to figure out why it's tracking whitespace changes while there are no whitespace changes.

I couldn't figure that out either. i tried using Sublime to switch my line ending setting between Unix/Windows/Mac OS9 but it didn't help... I was still seeing whitespace changes when I `git diff`

**Comment by mmmavis** [comment]
ah @ScottDowne I see why, it is my Sublime setting
`"trim_trailing_white_space_on_save": true`
I can temporarily disable it and update my PR again.  What do you think?

**Comment by ScottDowne** [comment]
Yeah, I don't like losing all the git blame info.

**Comment by ScottDowne** [comment]
Wait, is it saying there is trailing whitespace? I'll take another look at the file.

**Comment by mmmavis** [comment]
screen shot 2015-08-18 at 12 33 58 pm
yup i think that was it?

**Comment by ScottDowne** [comment]
I think it's the changes in the expect.jsx file that confuse me. I can see the changes in the other file and they make sense to me.

expect.jsx doesn't seem to have trailing whitespace.

**Comment by mmmavis** [comment]
> expect.jsx doesn't seem to have trailing whitespace

Probably due to me switching my line ending settings. 

Let me open up a new PR and see what it'll look like if I turn off trailing space trimming.  That way it's easier for us to compare and find out the cause.

**Comment by mmmavis** [comment]
Closing this PR.

@ScottDowne review this updated one instead plz https://github.com/mozilla/2015.mozillafestival.org/pull/167

**Pull request closed without merging**
