### PR TITLE
Update 'Mozilla Learning Networks' text

### PR DESCRIPTION
**Pull request by ioana-chiorean**
As per https://github.com/mozilla/2015.mozillafestival.org/issues/320#issuecomment-151909867
Should be ok but still r? cc @mmmavis

### CODE REVIEW

**Comment by ioana-chiorean** [comment]
Any input here @mmmavis?  will fix @KevZawacki proposal

**Comment by ioana-chiorean** [comment]
@KevZawacki can you check this pls - https://github.com/mozilla/2015.mozillafestival.org/pull/322/files 
If it is ok with you I will merge it - so it goes with the next push

**Comment by KevZawacki** [comment]
@ioana-chiorean Looks great -- thanks again!

**Comment by mmmavis** [comment]
sorry been crazily busy these days.  will check this out today!

**Comment by mmmavis** [comment]
r+ :tada: merging it now

**Comment by ioana-chiorean** [comment]
No worries! :tada:  happy to see it live!

**Pull request merged**
