### PR TITLE
Updated team page with Michelle's correction & Adding new icon

### PR DESCRIPTION
**Pull request by ioana-chiorean**

### CODE REVIEW

**Comment by cassiemc** [comment]
@ioana-chiorean Any chance you can share a screenshot with me? I don't have the site set up on my machine to check.

**Comment by ioana-chiorean** [comment]
The alignment can also be seen in the dropbox file. I think we need another version of it. 
cc @cassiemc 
screenshot from 2015-10-28 11 41 22

**Comment by cassiemc** [comment]
@ioana-chiorean I didn't think the extra space in an svg made a difference, but hopefully this update works! Here's a more tightly cropped version: https://www.dropbox.com/s/cxeclf77suf07ko/icon-youth-box.svg?dl=0

**Comment by cassiemc** [comment]
@ioana-chiorean please flag @mmmavis when you're ready for a review!

**Comment by ioana-chiorean** [comment]
New PR in #323 
Waiting for review from @mmmavis

**Pull request closed without merging**
